apiVersion: v2
name: portfolio
description: Helm chart for mehmetatademir.com portfolio website
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - portfolio
  - devops
  - kubernetes
maintainers:
  - name: Mehmet Atademir
    email: contact@mehmetatademir.com
