{{- if .Values.frontend.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "portfolio.fullname" . }}-frontend
  labels:
    {{- include "portfolio.frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  {{- if and (eq .Values.frontend.service.type "LoadBalancer") .Values.frontend.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.frontend.service.loadBalancerIP }}
  {{- end }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "portfolio.frontend.selectorLabels" . | nindent 4 }}
{{- end }}
